sonar.projectKey=reservas-ec-notification-service
sonar.projectName=ReservasEC - Notification Service
sonar.sources=.
sonar.inclusions=index.js,controllers/**,routes/**,services/**
sonar.exclusions=node_modules/**
sonar.sourceEncoding=UTF-8
