sonar.projectKey=reservas-ec-user-service
sonar.projectName=ReservasEC - User Service
sonar.sources=.
sonar.inclusions=index.js,middleware/**,models/**,routes/**
sonar.exclusions=node_modules/**
sonar.sourceEncoding=UTF-8
